### ISSUE TITLE
"Normal" authentication against back doesn't run

### ISSUE THREAD

**Issue by jamacia** [benbaran/adal-angular4#123]

**Comment by jamacia** [comment]
When I try to authenticate against bbdd not against azure, the call gives an error because the adal-angular4 interceptor intercepts it and of course is not authenticated against azure. What can I do to have two optiones: authenticate against azure or authenticate against back (wich reads from bbdd). The error is Error: Cannot send request to registered endpoint if the user is not authenticated.
message:"Cannot send request to registered endpoint if the user is not authenticated."
stack:"Error: Cannot send request to registered endpoint if the user is not authenticated
.\n    
at AdalInterceptor.intercept (http://localhost:4200/vendor.js:154633:19)\n    
at HttpInterceptorHandler.push../node_modules/@angular/common/fesm5/http.js.HttpInterceptorHandler.handle (http://localhost:4200/vendor.js:32890:33)\n    
at ErrorInterceptor.push../src/app/core/helpers/error.interceptor.ts.ErrorInterceptor.intercept 
(http://localhost:4200/main.js:458:21)\n    
at HttpInterceptorHandler.push../node_modules/@angular/common/fesm5/http.js.HttpInterceptorHandler.handle (http://localhost:4200/vendor.js:32890:33)\n    
at JwtInterceptor.push../src/app/core/helpers/jwt.interceptor.ts.JwtInterceptor.intercept (http://localhost:4200/main.js:514:21)\n    
at HttpInterceptorHandler.push../node_modules/@angular/common/fesm5/http.js.HttpInterceptorHandler.handle (http://localhost:4200/vendor.js:32890:33)\n    
at JwtInterceptor.push../node_modules/@auth0/angular-jwt/src/jwt.interceptor.js.JwtInterceptor.handleInterception (http://local..

Can you enable and disabled adal-angular4  with angular ?

Thanks !!!!.
