### ISSUE TITLE
ng build --prod Failing

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [benbaran/adal-angular4#26]
Hey, I'm using the latest version of ng and I'm getting this error when I try to build with the --prod flag:

`ERROR in Error: Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in C:/Source/Miscellaneous Web Sites/MetricsMonitoring/node_modules/adal-angular4/node_modules/@angular/core/core.d.ts, resolving symbol ɵa in C:/Source/Miscellaneous Web Sites/MetricsMonitoring/node_modules/adal-angular4/node_modules/@angular/http/http.d.ts, resolving symbol ɵa in C:/Source/Miscellaneous Web Sites/MetricsMonitoring/node_modules/adal-angular4/node_modules/@angular/http/http.d.ts`

Also, I'm getting these warnings when I run ng serve:

```
WARNING in ./node_modules/adal-angular4/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\Source\Miscellaneous Web Sites\MetricsMonitoring\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Source\Miscellaneous Web Sites\MetricsMonitoring\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\Source\Miscellaneous Web Sites\MetricsMonitoring\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\Source\Miscellaneous Web Sites\MetricsMonitoring\node_modules\webpack\lib\Compiler.js:506:17)
    at C:\Source\Miscellaneous Web Sites\MetricsMonitoring\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Source\Miscellaneous Web Sites\MetricsMonitoring\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\Source\Miscellaneous Web Sites\MetricsMonitoring\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/adal-angular4/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/adal-angular4/adal4-interceptor.js
 @ ./node_modules/adal-angular4/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ./node_modules/adal-angular4/node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\Source\Miscellaneous Web Sites\MetricsMonitoring\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Source\Miscellaneous Web Sites\MetricsMonitoring\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\Source\Miscellaneous Web Sites\MetricsMonitoring\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\Source\Miscellaneous Web Sites\MetricsMonitoring\node_modules\webpack\lib\Compiler.js:506:17)
    at C:\Source\Miscellaneous Web Sites\MetricsMonitoring\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Source\Miscellaneous Web Sites\MetricsMonitoring\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\Source\Miscellaneous Web Sites\MetricsMonitoring\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/adal-angular4/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/adal-angular4/adal4-interceptor.js
 @ ./node_modules/adal-angular4/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
```

Any idea on how I can fix this?

**Comment by Codefearingguy** [comment]
Am also stuck with the same thing.

**Comment by Codefearingguy** [comment]
Found a work around. Delete the local "node_modules" folder present inside the "node_modules/adal-angular4" folder.

**Comment by Codefearingguy** [comment]
Made 2 important changes to the package node_modules folder and things are working now.

1. Remove the local "node_modules" folder present inside the "node_modules/adal-angular4".
2. Inside "node_modules/adal-angular4" folder adal4.service.js replace:
var rxjs_1 = require("rxjs");
with 
var rxjs_1 = require("rxjs/Observable");

**Comment by pknetsfd** [comment]
@Codefearingguy Even I am trying to setup adal in angular 5 and going through the similar errors. After fixing the above 2, I got another error.  

ERROR Error: Uncaught (in promise): TypeError: rxjs_1.Observable.bindCallback is not a function
TypeError: rxjs_1.Observable.bindCallback is not a function
    at Adal4Service.acquireToken (webpack-internal:///../../../../adal-angular4/adal4.service.js:180)
    at AuthHttp.sendRequest (webpack-internal:///../../../../../src/app/shared/services/authhttp.service.ts:82)
    at AuthHttp.get (webpack-internal:///../../../../../src/app/shared/services/authhttp.service.ts:34)
    at UserInfoService.GetUserRolePermissions (webpack-internal:///../../../../../src/app/shared/services/userinfo.service.ts:61)
    at UserInfoService.GetAuthenticatedUserInfo (webpack-internal:///../../../../../src/app/shared/services/userinfo.service.ts:50)
    at AuthenticationGuard.canActivate (webpack-internal:///../../../../../src/app/shared/guards/authentication-guard.ts:33)
    at MapSubscriber.eval [as project] (webpack-internal:///../../../router/esm5/router.js:3837)
    at MapSubscriber._next (webpack-internal:///../../../../rxjs/_esm5/operators/map.js:82)
    at MapSubscriber.Subscriber.next (webpack-internal:///../../../../rxjs/_esm5/Subscriber.js:96)
    at ArrayObservable._subscribe (webpack-internal:///../../../../rxjs/_esm5/observable/ArrayObservable.js:121)
    at Adal4Service.acquireToken (webpack-internal:///../../../../adal-angular4/adal4.service.js:180)
    at AuthHttp.sendRequest (webpack-internal:///../../../../../src/app/shared/services/authhttp.service.ts:82)
    at AuthHttp.get (webpack-internal:///../../../../../src/app/shared/services/authhttp.service.ts:34)
    at UserInfoService.GetUserRolePermissions (webpack-internal:///../../../../../src/app/shared/services/userinfo.service.ts:61)
    at UserInfoService.GetAuthenticatedUserInfo (webpack-internal:///../../../../../src/app/shared/services/userinfo.service.ts:50)
    at AuthenticationGuard.canActivate (webpack-internal:///../../../../../src/app/shared/guards/authentication-guard.ts:33)
    at MapSubscriber.eval [as project] (webpack-internal:///../../../router/esm5/router.js:3837)
    at MapSubscriber._next (webpack-internal:///../../../../rxjs/_esm5/operators/map.js:82)
    at MapSubscriber.Subscriber.next (webpack-internal:///../../../../rxjs/_esm5/Subscriber.js:96)
    at ArrayObservable._subscribe (webpack-internal:///../../../../rxjs/_esm5/observable/ArrayObservable.js:121)
    at resolvePromise (webpack-internal:///../../../../zone.js/dist/zone.js:824)
    at resolvePromise (webpack-internal:///../../../../zone.js/dist/zone.js:795)
    at eval (webpack-internal:///../../../../zone.js/dist/zone.js:873)
    at ZoneDelegate.invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:425)
    at Object.onInvokeTask (webpack-internal:///../../../core/esm5/core.js:4816)
    at ZoneDelegate.invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:424)
    at Zone.runTask (webpack-internal:///../../../../zone.js/dist/zone.js:192)
    at drainMicroTaskQueue (webpack-internal:///../../../../zone.js/dist/zone.js:602)
    at <anonymous>

**Comment by karuppasamy20** [comment]
same issue on mine...
please any solution for that

**Comment by subhankar99** [comment]
Use https://www.npmjs.com/package/adal-angular4plus -- This is compatible with latest version of angular and ng CLI

**Comment by skorunka** [comment]
@pknetsfd  Adding this line in a ts file which is using the library, solved the problem `import 'rxjs/add/observable/bindCallback';` Im not saying it is a right solution :(. The library just does not support latest rxJs and ng5

**Comment by skorunka** [comment]
@subhankar99 `adal-angular4plus` gices me this error:

```
ERROR in node_modules/adal-angular4plus/adal4.service.d.ts(40,25): error TS2503: Cannot find namespace 'adal'.
node_modules/adal-angular4plus/adal4.service.d.ts(48,22): error TS2503: Cannot find namespace 'adal'.
```

Any idea what I'm missing? Thank you.

**Comment by subhankar99** [comment]
@skorunka..not sure. Plz upload your code somewhere so that I can check

**Comment by skorunka** [comment]
@subhankar99 Hi, unfortunately I cannot, it is a company code. I don't have a time to create a repro git repository at the moment :(.

**Comment by subhankar99** [comment]
Ok. I am also using this package in my prod and it builds correctly.

**Comment by ggit2018** [comment]
ERROR in Metadata version mismatch for module C:/cs/CSM/node_modules/adal-angular4plus/node_modules/@angular/core/core.d.ts, found version 4, expected 3.  I am using Visual Studio 2017 along with ASP.net core 2.0 for creating an authentication application using angular4 and adal-angular4plus.  I am able to build and run the program without any issues. 

The error comes only when I try to 'Publish' using VS 2017. 


package.json
---------------
{
  "name": "CSM",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "test": "karma start ClientApp/test/karma.conf.js"
  },
  "devDependencies": {
    "@angular/animations": "4.2.5",
    "@angular/common": "4.2.5",
    "@angular/compiler": "4.2.5",
    "@angular/compiler-cli": "4.2.5",
    "@angular/core": "4.2.5",
    "@angular/forms": "4.2.5",
    "@angular/http": "4.2.5",
    "@angular/platform-browser": "4.2.5",
    "@angular/platform-browser-dynamic": "4.2.5",
    "@angular/platform-server": "4.2.5",
    "@angular/router": "4.2.5",
    "@ngtools/webpack": "1.5.0",
    "@types/chai": "4.0.1",
    "@types/jasmine": "2.5.53",
    "@types/webpack-env": "1.13.0",
    "angular2-router-loader": "0.3.5",
    "angular2-template-loader": "0.6.2",
    "aspnet-prerendering": "^3.0.1",
    "aspnet-webpack": "^2.0.1",
    "awesome-typescript-loader": "3.2.1",
    "bootstrap": "^3.3.7",
    "chai": "4.0.2",
    "css": "2.2.1",
    "css-loader": "0.28.4",
    "es6-shim": "0.35.3",
    "event-source-polyfill": "0.0.9",
    "expose-loader": "0.7.3",
    "extract-text-webpack-plugin": "2.1.2",
    "file-loader": "0.11.2",
    "font-awesome": "^4.7.0",
    "html-loader": "0.4.5",
    "isomorphic-fetch": "2.2.1",
    "jasmine-core": "2.6.4",
    "jquery": "3.2.1",
    "json-loader": "0.5.4",
    "karma": "1.7.0",
    "karma-chai": "0.1.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.1.0",
    "karma-webpack": "2.0.3",
    "preboot": "4.5.2",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.4.2",
    "style-loader": "0.18.2",
    "to-string-loader": "1.1.5",
    "typescript": "2.4.1",
    "url-loader": "0.5.9",
    "webpack": "2.5.1",
    "webpack-hot-middleware": "2.18.2",
    "webpack-merge": "4.1.0",
    "zone.js": "0.8.12"
  },
  "dependencies": {
    "@angular/cli": "^1.6.3",
    "adal-angular4plus": "^1.0.1",
    "primeng": "^4.1.0"
  }
}

Publish output fragment: 
================
CSM -> C:\cs\CSM\bin\Any CPU\Release\netcoreapp2.0\CSM.dll
"dotnet" exec --runtimeconfig "C:\cs\CSM\bin\Any CPU\Release\netcoreapp2.0\CSM.runtimeconfig.json" --depsfile "C:\cs\CSM\bin\Any CPU\Release\netcoreapp2.0\CSM.deps.json" "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.1\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll" @"obj\Any CPU\Release\netcoreapp2.0\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"
npm install
npm WARN @angular-devkit/schematics@0.0.43 requires a peer of rxjs@^5.5.2 but none is installed. You must install peer dependencies yourself.
up to date in 5.538s

node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js --env.prod
Hash: 206eac77ac26ca4f08fe3a14b3c79dfdd47cacbb
Version: webpack 2.5.1
Child
    Hash: 206eac77ac26ca4f08fe
    Time: 21443ms
                                   Asset     Size  Chunks                    Chunk Names
    674f50d287a8c48dc19ba404d20fe713.eot   166 kB          [emitted]         
    912ec66d7572ff821749319396470bde.svg   444 kB          [emitted]  [big]  
    b06871f281fee6b241d60582ae9369b9.ttf   166 kB          [emitted]         
    89889688147bd7575d6327160d64e760.svg   109 kB          [emitted]         
                               vendor.js  1.72 MB       0  [emitted]  [big]  vendor
                              vendor.css   917 kB       0  [emitted]  [big]  vendor
    
    WARNING in ./~/adal-angular4plus/~/@angular/core/esm5/core.js
    6541:15-36 Critical dependency: the request of a dependency is an expression
    
    WARNING in ./~/adal-angular4plus/~/@angular/core/esm5/core.js
    6561:15-102 Critical dependency: the request of a dependency is an expression
Child
    Hash: 3a14b3c79dfdd47cacbb
    Time: 21383ms
                                   Asset    Size  Chunks                    Chunk Names
    89889688147bd7575d6327160d64e760.svg  109 kB          [emitted]         
    674f50d287a8c48dc19ba404d20fe713.eot  166 kB          [emitted]         
    912ec66d7572ff821749319396470bde.svg  444 kB          [emitted]  [big]  
    b06871f281fee6b241d60582ae9369b9.ttf  166 kB          [emitted]         
                               vendor.js  7.1 MB       0  [emitted]  [big]  vendor
node node_modules/webpack/bin/webpack.js --env.prod
Hash: 7c6b35cb9cc073d78bd1e242d2b377746ea93733
Version: webpack 2.5.1
Child
    Hash: 7c6b35cb9cc073d78bd1
    Time: 4151ms
             Asset    Size  Chunks             Chunk Names
    main-client.js  115 kB       0  [emitted]  main-client
    
    ERROR in Metadata version mismatch for module C:/cs/CSM/node_modules/adal-angular4plus/node_modules/@angular/core/core.d.ts, found version 4, expected 3
    
    ERROR in ./ClientApp/boot.browser.ts
Module not found(0,0): Error : Can't resolve './../$$_gendir/ClientApp/app/app.browser.module.ngfactory' in 'C:\cs\CSM\ClientApp'
     @ ./ClientApp/boot.browser.ts 6:0-95
Child
    Hash: e242d2b377746ea93733
    Time: 4155ms
             Asset     Size  Chunks                    Chunk Names
    main-server.js  1.81 MB       0  [emitted]  [big]  main-server
    
    ERROR in Metadata version mismatch for module C:/cs/CSM/node_modules/adal-angular4plus/node_modules/@angular/core/core.d.ts, found version 4, expected 3
    
    ERROR in ./ClientApp/boot.server.ts
Module not found(0,0): Error : Can't resolve './../$$_gendir/ClientApp/app/app.server.module.ngfactory' in 'C:\cs\CSM\ClientApp'
     @ ./ClientApp/boot.server.ts 8:0-94
C:\cs\CSM\CSM.csproj(135,5): Error MSB3073: The command "node node_modules/webpack/bin/webpack.js --env.prod" exited with code 2.

2>Publish failed due to build errors. Check the error list for more details.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped =======

What I am missing ? 


thanks

**Comment by Lecha1** [comment]
subhankar99 again you man with your plus? I already told you in details where is the problem. Please stop wasting peoples time with some useless stuff. It works in my what is that for an answer first of all?

**Comment by benbaran** [comment]
This has been fixed in the v2 library.
